# your domain
domain: free.iam7.tk

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - http://free.iam7.tk/source.yaml
