# your domain
domain: xiao7ss.herokuapp.com

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  - source.yaml
  # use web file
  - http://xiao7ss.herokuapp.com/source.yaml
